import { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import RFB from "@novnc/novnc";
import { applyStatusToDesktop, desktopButtonLabel, disconnectState, fullscreenButtonLabel, passwordForConnection, workstationButtonLabel, type DesktopState } from "./connection";
import "./styles.css";

type State = DesktopState;
type Status = { state: State; desktop_ready: boolean; image: string; container_name: string; workspace: string; image_id?: string; image_ref?: string; gpu_uuids: string[]; desktop_capable: boolean; csrf_token: string; message?: string };
type Image = { id: string; references: string[]; display_reference: string; size: number; architecture: string; desktop_capable: boolean };
type GPU = { uuid: string; index: number; name: string; memory_total_mib: number };
type Inventory = { images: Image[]; gpus: GPU[]; gpu_diagnostic?: string };
const api = async <T,>(path: string, csrf?: string, init?: RequestInit): Promise<T> => { const response = await fetch(path, { credentials: "same-origin", ...init, headers: { "content-type": "application/json", ...(csrf ? { "x-csrf-token": csrf } : {}), ...init?.headers } }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Request failed"); return data; };

function LaunchSetup({ inventory, onStart }: { inventory: Inventory; onStart: (image: string, gpus: string[], replace: boolean) => void }) {
  const [image, setImage] = useState(""); const [gpus, setGpus] = useState<string[]>([]);
  const selected = inventory.images.find((candidate) => candidate.id === image);
  const all = inventory.gpus.length > 0 && gpus.length === inventory.gpus.length;
  const toggleGpu = (uuid: string) => setGpus((current) => current.includes(uuid) ? current.filter((value) => value !== uuid) : [...current, uuid]);
  return <div className="launch-setup"><h1>Launch a workstation</h1><p>Select a local image and optional NVIDIA GPUs. CPU-only is the default.</p>
    <label>Local image<select value={image} onChange={(event) => setImage(event.target.value)}><option value="">Choose an image…</option>{inventory.images.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.display_reference}</option>)}</select></label>
    {selected && <p className="capability">{selected.desktop_capable ? "Desktop capable (contract v1)" : "Shell-only image — desktop controls will be unavailable."}</p>}
    <fieldset><legend>GPUs</legend>{inventory.gpu_diagnostic && <p className="diagnostic">{inventory.gpu_diagnostic}</p>}<label className="check"><input type="checkbox" checked={all} disabled={!inventory.gpus.length} onChange={() => setGpus(all ? [] : inventory.gpus.map((gpu) => gpu.uuid))} /> Select all ({inventory.gpus.length})</label>{inventory.gpus.map((gpu) => <label className="check" key={gpu.uuid}><input type="checkbox" checked={gpus.includes(gpu.uuid)} onChange={() => toggleGpu(gpu.uuid)} /> GPU {gpu.index}: {gpu.name} · {gpu.memory_total_mib} MiB</label>)}<p>{gpus.length ? `${gpus.length} GPU${gpus.length === 1 ? "" : "s"} selected` : "CPU-only"}</p></fieldset>
    <button className="primary" disabled={!image} onClick={() => onStart(image, gpus, false)}>Start workstation</button></div>;
}

function App() {
  const canvas = useRef<HTMLDivElement>(null); const rfb = useRef<RFB | null>(null); const vncPassword = useRef<string | null>(null); const closingDesktop = useRef(false);
  const [status, setStatus] = useState<Status | null>(null); const [inventory, setInventory] = useState<Inventory | null>(null); const [state, setState] = useState<State>("loading"); const [message, setMessage] = useState("Checking workstation…"); const [passwordAction, setPasswordAction] = useState<"connect" | "reset" | null>(null); const [password, setPassword] = useState(""); const [canResetPassword, setCanResetPassword] = useState(false); const [fullscreen, setFullscreen] = useState(false);
  const refresh = async () => { try { const next = await api<Status>("/api/workstation"); setStatus((current) => current ? { ...current, ...next } : next); if (applyStatusToDesktop(state)) { setState(next.state); setMessage(next.message || (next.state === "running" ? "Workstation is ready" : "")); } if (next.state === "absent") setInventory(await api<Inventory>("/api/host/inventory")); } catch { setState("unavailable"); setMessage("Workbench is unavailable. Check that Docker is running."); } };
  useEffect(() => { void refresh(); return () => rfb.current?.disconnect(); }, []);
  const mutate = async (endpoint: "start" | "stop", launch?: { image: string; gpus: string[]; replace: boolean }) => { if (!status) return; if (endpoint === "stop" && state === "connected" && !window.confirm("Stop the workstation and disconnect the desktop?")) return; try { setState("connecting"); setMessage(endpoint === "start" ? "Starting workstation…" : "Stopping workstation…"); const body = launch ? JSON.stringify({ image: launch.image, gpu_uuids: launch.gpus, replace: launch.replace }) : undefined; const next = await api<Status>(`/api/workstation/${endpoint}`, status.csrf_token, { method: "POST", body }); setStatus({ ...status, ...next }); setState(next.state); setMessage(next.state === "running" ? "Workstation is ready" : "Workstation stopped"); if (endpoint === "stop") { closingDesktop.current = true; rfb.current?.disconnect(); } } catch (error) { if (endpoint === "start" && error instanceof Error && error.message.includes("--replace") && window.confirm("Replacing discards the old container filesystem but keeps /workspace and /state. Replace it?")) { if (launch) await mutate("start", { ...launch, replace: true }); return; } setState("failed"); setMessage(error instanceof Error ? error.message : "Action failed"); } };
  const openDesktop = async (supplied?: string) => { const connectionPassword = passwordForConnection(supplied ?? password, vncPassword.current); if (!status || !connectionPassword || !status.desktop_capable) return; try { setPasswordAction(null); setState("connecting"); const session = await api<{ session_id: string }>("/api/desktop/sessions", status.csrf_token, { method: "POST", body: JSON.stringify({ password: connectionPassword }) }); const scheme = location.protocol === "https:" ? "wss" : "ws"; rfb.current?.disconnect(); const client = new RFB(canvas.current!, `${scheme}://${location.host}/api/desktop/sessions/${session.session_id}/ws`, { credentials: { password: connectionPassword } }); vncPassword.current = connectionPassword; setPassword(""); let authFailed = false; client.scaleViewport = true; client.viewOnly = false; client.addEventListener("connect", () => { setCanResetPassword(false); setState("connected"); setMessage("Desktop connected"); }); client.addEventListener("securityfailure", () => { authFailed = true; vncPassword.current = null; setCanResetPassword(true); setState("failed"); setMessage("VNC authentication failed."); }); client.addEventListener("disconnect", () => { const next = disconnectState(authFailed, closingDesktop.current); closingDesktop.current = false; if (next) { setState(next); setMessage("Desktop disconnected."); } }); rfb.current = client; } catch (error) { setState("failed"); setMessage(error instanceof Error ? error.message : "Desktop connection failed"); } };
  const resetDesktopPassword = async () => { if (!status || !password) return; const replacement = password; try { const next = await api<Status>("/api/desktop/password", status.csrf_token, { method: "POST", body: JSON.stringify({ password: replacement }) }); setStatus({ ...status, ...next }); vncPassword.current = replacement; setPassword(""); setPasswordAction(null); await openDesktop(replacement); } catch (error) { setMessage(error instanceof Error ? error.message : "Password reset failed"); } };
  const running = status?.state === "running"; const desktop = status?.desktop_capable; const label = state === "running" ? "Ready" : state === "loading" ? "Checking" : state;
  return <main className={fullscreen ? "fullscreen-active" : ""}><header className="app-header"><div className="brand"><strong>Docker Workbench</strong><span>{status?.container_name || "docker-ws"}</span></div></header><aside className="sidebar"><div className={`status ${state}`}><i /><span>{label}</span><button className="status-refresh" onClick={() => void refresh()}>↻</button></div><nav className="actions"><button className={running ? "toggle-on" : "primary"} disabled={!status || state === "connecting" || !running} onClick={() => void mutate("stop")}>■ Stop workstation</button><button className={state === "connected" ? "toggle-on" : "primary"} disabled={!running || !desktop} title={desktop ? "Open desktop" : "The selected image is shell-only"} onClick={() => state === "connected" ? rfb.current?.disconnect() : (vncPassword.current ? void openDesktop() : setPasswordAction("connect"))}>▣ {desktopButtonLabel(state)}</button><button className="quiet" onClick={async () => { if (document.fullscreenElement) await document.exitFullscreen(); else await document.documentElement.requestFullscreen(); setFullscreen(!fullscreen); }}>⛶ {fullscreenButtonLabel(fullscreen)}</button></nav></aside><section className="desktop"><div ref={canvas} className="canvas" />{state !== "connected" && <div className="empty">{status?.state === "absent" && inventory ? <LaunchSetup inventory={inventory} onStart={(image, gpus, replace) => void mutate("start", { image, gpus, replace })} /> : <><h1>{desktop ? "Desktop not connected" : "Shell workstation"}</h1><p>{desktop ? message : "This image does not provide the desktop contract. Use docker-ws enter for a root shell."}</p>{canResetPassword && <button onClick={() => setPasswordAction("reset")}>Reset VNC password</button>}</>}</div>}</section>{passwordAction && <div className="modal" role="dialog"><form onSubmit={(event) => { event.preventDefault(); passwordAction === "reset" ? void resetDesktopPassword() : void openDesktop(); }}><h2>{passwordAction === "reset" ? "Reset VNC password" : "Connect desktop"}</h2><input autoFocus type="password" minLength={passwordAction === "reset" ? 6 : undefined} maxLength={passwordAction === "reset" ? 8 : undefined} value={password} onChange={(event) => setPassword(event.target.value)} required /><button className="quiet" type="button" onClick={() => setPasswordAction(null)}>Cancel</button><button className="primary">{passwordAction === "reset" ? "Reset and connect" : "Connect"}</button></form></div>}</main>;
}
createRoot(document.getElementById("root")!).render(<App />);
